name: flutter_ecosed_example
description: "Demonstrates how to use the flutter_ecosed plugin."
publish_to: "none"

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_boost:
    git:
        url: 'https://github.com/alibaba/flutter_boost.git'
        ref: '5.0.2'
  flutter_ecosed:
    path: ../
  webview_flutter: ^4.8.0
  url_launcher: ^6.2.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
