name: flutter_ecosed_example
description: "Demonstrates how to use the flutter_ecosed plugin."
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ecosed:
    path: ../
  dynamic_color: ^1.7.0
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  device_preview: ^1.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
