[package]
name = "flutter_ecosed"
version = "0.0.1"
authors = ["wyq0918dev <wyq0918dev@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.1.0"
